table mapp_api_query_7241_09_clone
	lineageTag: 07e379a0-02e5-4f8b-adc7-a567f968ae29

	measure 'avg. time_clone' =
			
			VAR TotalSeconds = ROUND(AVERAGE('mapp_api_query_7241_09_clone'[custom_formula_1000229]) * 60, 0)
			VAR Minutes = TotalSeconds / 60
			VAR Seconds = MOD(TotalSeconds, 60)
			VAR MinutesText = RIGHT("0" & INT(Minutes), 2)
			VAR SecondsText = RIGHT("0" & INT(Seconds), 2)
			RETURN MinutesText & ":" & SecondsText
		lineageTag: b78960ff-e755-43ef-9776-d6a82a2ae783

	measure 'avg. time_minutes_clone' =
			
			VAR TotalSeconds = ROUND(AVERAGE('mapp_api_query_7241_09_clone'[custom_formula_1000229]) * 60, 0)
			VAR Minutes = TotalSeconds / 60
			RETURN Minutes
		lineageTag: f0538791-50c9-4919-8ac2-60ec1616c77f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Minutes_clone =
			
			VAR Minutes = SUM('mapp_api_query_7241_09_clone'[pages_pageImpressions])*mapp_api_query_7241_09_clone[avg. time_minutes_clone]
			RETURN Minutes
		lineageTag: 26813c3b-1157-47a1-89eb-1babb9434015

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column session_id
		dataType: string
		lineageTag: 30d601ca-d0a3-4585-a9c3-3ae27998088a
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column pages
		dataType: string
		lineageTag: 17c46e11-cc72-4a7b-89f4-5a872cd83ab9
		summarizeBy: none
		sourceColumn: pages

		annotation SummarizationSetBy = Automatic

	column pages_pageImpressions
		dataType: int64
		formatString: 0
		lineageTag: d8432e45-355c-4dba-8809-0bd821f39c71
		summarizeBy: sum
		sourceColumn: pages_pageImpressions

		annotation SummarizationSetBy = Automatic

	column visits
		dataType: int64
		formatString: 0
		lineageTag: d1276a73-bc62-4005-8425-be7ee79b2864
		summarizeBy: sum
		sourceColumn: visits

		annotation SummarizationSetBy = Automatic

	column custom_formula_1000229
		dataType: double
		lineageTag: 853028ad-a7ff-47ca-877f-f3f426730cfc
		summarizeBy: sum
		sourceColumn: custom_formula_1000229

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pages_entries
		dataType: int64
		formatString: 0
		lineageTag: c5caa220-cecf-4805-9ccf-455f4aaaa6aa
		summarizeBy: sum
		sourceColumn: pages_entries

		annotation SummarizationSetBy = Automatic

	column pages_exits
		dataType: int64
		formatString: 0
		lineageTag: 0ece0157-4459-48ab-85c0-fb16ac1f2246
		summarizeBy: sum
		sourceColumn: pages_exits

		annotation SummarizationSetBy = Automatic

	column visits_bounces
		dataType: int64
		formatString: 0
		lineageTag: b5105504-8069-40e1-b126-b77a9addc7c8
		summarizeBy: sum
		sourceColumn: visits_bounces

		annotation SummarizationSetBy = Automatic

	column visitors
		dataType: int64
		formatString: 0
		lineageTag: 42a674dc-35ce-4346-b069-30e2c6a49128
		summarizeBy: sum
		sourceColumn: visitors

		annotation SummarizationSetBy = Automatic

	column WpPostId
		dataType: string
		lineageTag: cf8152f3-eb53-4b9b-a95c-892f212955dd
		summarizeBy: none
		sourceColumn: WpPostId

		annotation SummarizationSetBy = Automatic

	partition mapp_api_query_7241_09_clone = m
		mode: import
		source =
				let
				    Quelle = Databricks.Catalogs("adb-4119964566130471.11.azuredatabricks.net", "/sql/1.0/warehouses/59a74cf19690258c", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation=null]),
				    swi_audience_prd_Database = Quelle{[Name="swi_audience_prd",Kind="Database"]}[Data],
				    swiplus_Schema = swi_audience_prd_Database{[Name="swiplus",Kind="Schema"]}[Data],
				    mapp_api_query_7241_08_Table = swiplus_Schema{[Name="mapp_api_query_7241_09_clone",Kind="Table"]}[Data]
				in
				    mapp_api_query_7241_08_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

