table mapp_api_query_7241_08
	lineageTag: 46c82ecc-4db6-4201-ba1e-ba2d6f0c0deb

	measure 'avg. Time Media (mm:ss)' = ```
			
			VAR SecondsTotal = 
			    DIVIDE(
			        SUM('mapp_api_query_7241_08'[media_playbackTime]),
			        SUM('mapp_api_query_7241_08'[media_views])
			    )
			VAR Minutes = INT(SecondsTotal / 60)
			VAR Seconds = MOD(ROUND(SecondsTotal, 0), 60)
			RETURN 
			FORMAT(Minutes, "00") & ":" & FORMAT(Seconds, "00")
			```
		lineageTag: 5f31f680-1507-4e9b-9b5a-c2813d0944af

	measure media_viewsCompletionRate_1 = SUM(mapp_api_query_7241_08[media_viewsComplete]) / SUM(mapp_api_query_7241_08[media_views])
		formatString: 0%;-0%;0%
		lineageTag: f61b6c8e-8264-4e80-83bc-92ea6facf770

	column session_id
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 69aae45a-9d91-4a57-a5cb-2bf55344bb2f
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column media
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 19944135-d0ed-4b1e-9114-c4723be77fb2
		summarizeBy: none
		sourceColumn: media

		annotation SummarizationSetBy = Automatic

	column media_category_text_1
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 22c6f37a-39b8-496a-84e0-1b93e07c6fda
		summarizeBy: none
		sourceColumn: media_category_text_1

		annotation SummarizationSetBy = Automatic

	column media_category_text_15
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 25120fdb-3b1e-4c20-a481-021e5dc4cd03
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: media_category_text_15

		annotation SummarizationSetBy = Automatic

	column media_category_text_16
		dataType: string
		sourceProviderType: nvarchar(65535)
		lineageTag: 05daa8eb-f779-4b80-baa8-e057a06e89c1
		summarizeBy: none
		sourceColumn: media_category_text_16

		annotation SummarizationSetBy = Automatic

	column media_views
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 078bb1af-74ac-4a20-8b84-6a98d1d8d535
		summarizeBy: sum
		sourceColumn: media_views

		annotation SummarizationSetBy = Automatic

	column custom_metric_1000093
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 9fe6597f-be7a-4d68-873c-642665d1b8f9
		summarizeBy: sum
		sourceColumn: custom_metric_1000093

		annotation SummarizationSetBy = Automatic

	column custom_metric_1000088
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 9ff79e55-70d1-4b8c-9f6c-83f898ed05f6
		summarizeBy: sum
		sourceColumn: custom_metric_1000088

		annotation SummarizationSetBy = Automatic

	column custom_metric_1000089
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2e525202-c8a8-4927-920f-8e9b0875def9
		summarizeBy: sum
		sourceColumn: custom_metric_1000089

		annotation SummarizationSetBy = Automatic

	column custom_metric_1000090
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3c8d75fa-ca93-43fd-89d0-b85948fc0f80
		summarizeBy: sum
		sourceColumn: custom_metric_1000090

		annotation SummarizationSetBy = Automatic

	column custom_metric_1000091
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 1389abc5-bab0-4aeb-a8a5-1c0f0378f36a
		summarizeBy: sum
		sourceColumn: custom_metric_1000091

		annotation SummarizationSetBy = Automatic

	column media_viewsComplete
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ecf25146-a224-4680-9202-37c0d779a3a4
		summarizeBy: sum
		sourceColumn: media_viewsComplete

		annotation SummarizationSetBy = Automatic

	column media_playbackTime
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e2975b7c-961a-4548-a3ee-0e3c56de77e5
		summarizeBy: sum
		sourceColumn: media_playbackTime

		annotation SummarizationSetBy = Automatic

	column SRF_Link =
			
			"https://www.srf.ch/play/tv/-/video/-?urn=" & mapp_api_query_7241_08[media]
		lineageTag: 3abbb1eb-fb28-42fd-8e13-563ff1f39dc7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column media_playbackTime_minutes = ```
			mapp_api_query_7241_08[media_playbackTime]/60 
			```
		formatString: 0
		lineageTag: 741ea84a-96cf-4325-8eff-a672a51b5a78
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column media_viewsCompletionRate = mapp_api_query_7241_08[media_viewsComplete] / mapp_api_query_7241_08[media_views]
		lineageTag: 179b3845-d47b-4393-9e95-51d71d51a0af
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition mapp_api_query_7241_08 = m
		mode: import
		source =
				let
				    Quelle = Databricks.Catalogs("adb-4119964566130471.11.azuredatabricks.net", "/sql/1.0/warehouses/59a74cf19690258c", null),
				    swi_audience_prd_Database = Quelle{[Name="swi_audience_prd",Kind="Database"]}[Data],
				    swiplus_Schema = swi_audience_prd_Database{[Name="swiplus",Kind="Schema"]}[Data],
				    mapp_api_query_7241_08_Table = swiplus_Schema{[Name="mapp_api_query_7241_08",Kind="Table"]}[Data]
				in
				    mapp_api_query_7241_08_Table

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

